import polars as pl

data = [
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-apartamento-2-quartos-com-piscina-pinheiros-zona-oeste-sao-paulo-sp-68m2-id-2868482178/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 68 m², 2 quartos, 3 banheiros, 2 vagas em\nCerqueira César, São Paulo",
        "street": "Rua Cristiano Viana",
        "area": "Tamanho do imóvel\n68 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": "Quantidade de vagas de garagem\n2",
        "price": "R$ 4.000/mês",
        "fees": "Cond. R$ 1.500 • IPTU R$ 270",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-casa-2-quartos-com-cozinha-vila-assuncao-santo-andre-sp-209m2-id-2825095088/?source=ranking%2Crp",
        "location": "Casa para alugar com 209 m², 2 quartos, 2 banheiros, 8 vagas em\nVila Assunção, Santo André",
        "street": "Rua Florianópolis",
        "area": "Tamanho do imóvel\n209 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n8",
        "price": "R$ 5.600/mês",
        "fees": "IPTU R$ 210",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-conjunto-comercial-sala-mobiliado-vila-olimpia-zona-sul-sao-paulo-sp-841m2-id-2658801782/?source=ranking%2Crp",
        "location": "Sala/Conjunto para alugar com 841 m², 17 banheiros, 17 vagas em\nVila Olímpia, São Paulo",
        "street": "Rua Alvorada",
        "area": "Tamanho do imóvel\n841 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n17",
        "parking": "Quantidade de vagas de garagem\n17",
        "price": "R$ 100.000/mês",
        "fees": "Cond. R$ 16.829 • IPTU R$ 12.622",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-sobrados-3-quartos-com-quintal-vila-ivone-sao-paulo-200m2-id-2865248974/?source=ranking%2Crp",
        "location": "Sobrado para alugar com 200 m², 3 quartos, 4 banheiros, 6 vagas em\nVila Ivone, São Paulo",
        "street": "Rua Ângelo Agostini",
        "area": "Tamanho do imóvel\n200 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n4",
        "parking": "Quantidade de vagas de garagem\n6",
        "price": "R$ 4.000/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-com-piscina-jardim-dom-jose-sao-paulo-45m2-id-2848692531/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 45 m², 2 quartos, 1 banheiro, 1 vaga em\nJardim Dom José, São Paulo",
        "street": "Rua Luís de Oliveira",
        "area": "Tamanho do imóvel\n45 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 1.800/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-conjunto-comercial-sala-1-quarto-loteamento-alphaville-campinas-campinas-40m2-id-2865092277/?source=ranking%2Crp",
        "location": "Sala/Conjunto para alugar com 40 m², 1 quarto, 1 banheiro, 1 vaga em\nLoteamento Alphaville Campinas, Campinas",
        "street": "Rua Umbu",
        "area": "Tamanho do imóvel\n40 m²",
        "bedrooms": "Quantidade de quartos\n1",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 2.000/mês",
        "fees": "Cond. R$ 821 • IPTU R$ 200",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-conjunto-comercial-sala-com-interfone-jardim-das-acacias-sao-paulo-406m2-id-2729722462/?source=ranking%2Crp",
        "location": "Sala/Conjunto para alugar com 406 m², 12 banheiros, 12 vagas em\nJardim das Acácias, São Paulo",
        "street": "Avenida Roque Petroni Júnior",
        "area": "Tamanho do imóvel\n406 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n12",
        "parking": "Quantidade de vagas de garagem\n12",
        "price": "R$ 37.000/mês",
        "fees": "Cond. R$ 10.077 • IPTU R$ 6.800",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-parque-santos-dumont-votorantim-1800m2-id-2743480119/?source=ranking%2Crp",
        "location": "Lote/Terreno para alugar com 1800 m² em\nParque Santos Dumont, Votorantim",
        "street": "",
        "area": "Tamanho do imóvel\n1800 m²",
        "bedrooms": None,
        "bathrooms": None,
        "parking": None,
        "price": "R$ 6.500/mês",
        "fees": "IPTU R$ 400",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-loja-salao-com-porcelanato-centro-campos-dos-goytacazes-179m2-id-2865561309/?source=ranking%2Crp",
        "location": "Ponto comercial/Loja/Box para alugar com 179 m², 3 banheiros em\nCentro, Campos dos Goytacazes",
        "street": "",
        "area": "Tamanho do imóvel\n179 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": None,
        "price": "R$ 6.000/mês",
        "fees": "IPTU R$ 369",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-sobrados-3-quartos-mobiliado-centro-quatro-barras-110m2-id-2864699768/?source=ranking%2Crp",
        "location": "Sobrado para alugar com 110 m², 3 quartos, 1 banheiro, 2 vagas em\nCentro, Quatro Barras",
        "street": "Rua Padre Gustavo Gian Pietro",
        "area": "Tamanho do imóvel\n110 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n2",
        "price": "R$ 2.800/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-mobiliado-parque-industrial-campinas-33m2-id-2863995269/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 33 m², 1 quarto, 1 banheiro, 1 vaga em\nParque Industrial, Campinas",
        "street": "Rua Professor Orestes Carlos Segallio",
        "area": "Tamanho do imóvel\n33 m²",
        "bedrooms": "Quantidade de quartos\n1",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 3.000/mês",
        "fees": "Cond. R$ 500 • IPTU R$ 100",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-sobrados-3-quartos-jardim-sao-carlos-campinas-238m2-id-2863290462/?source=ranking%2Crp",
        "location": "Sobrado para alugar com 238 m², 3 quartos, 3 banheiros, 4 vagas em\nJardim São Carlos, Campinas",
        "street": "Rua Alfredo Ribeiro Nogueira",
        "area": "Tamanho do imóvel\n238 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": "Quantidade de vagas de garagem\n4",
        "price": "R$ 6.900/mês",
        "fees": "IPTU R$ 360",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-com-piscina-pituba-salvador-78m2-id-2864937553/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 78 m², 2 quartos, 3 banheiros, 2 vagas em\nPituba, Salvador",
        "street": "Rua Manoel Andrade",
        "area": "Tamanho do imóvel\n78 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": "Quantidade de vagas de garagem\n2",
        "price": "R$ 3.800/mês",
        "fees": "Cond. R$ 1.550 • IPTU R$ 220",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-loja-salao-com-lavabo-horto-campos-dos-goytacazes-120m2-id-2865562277/?source=ranking%2Crp",
        "location": "Ponto comercial/Loja/Box para alugar com 120 m², 3 banheiros, 6 vagas em\nHorto, Campos dos Goytacazes",
        "street": "",
        "area": "Tamanho do imóvel\n120 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": "Quantidade de vagas de garagem\n6",
        "price": "R$ 5.500/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-casa-3-quartos-com-churrasqueira-cibratel-ii-itanhaem-75m2-id-2868057300/?source=ranking%2Crp",
        "location": "Casa para alugar com 75 m², 3 quartos, 1 banheiro, 3 vagas em\nCibratel II, Itanhaém",
        "street": "Rua Espirito Santo",
        "area": "Tamanho do imóvel\n75 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n3",
        "price": "R$ 2.300/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-piscina-aurora-londrina-63m2-id-2866565094/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 63 m², 3 quartos, 1 banheiro, 1 vaga em\nAurora, Londrina",
        "street": "Avenida José Gabriel de Oliveira",
        "area": "Tamanho do imóvel\n63 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 2.100/mês",
        "fees": "Cond. R$ 480",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-galpao-deposito-armazem-com-cozinha-parque-sao-cristovao-taubate-800m2-id-2845325063/?source=ranking%2Crp",
        "location": "Galpão/Depósito/Armazém para alugar com 800 m², 1 banheiro em\nParque São Cristóvão, Taubaté",
        "street": "",
        "area": "Tamanho do imóvel\n800 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": None,
        "price": "R$ 2.500/mês",
        "fees": "IPTU R$ 150",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-com-piscina-jardim-paulista-sao-paulo-84m2-id-2759344521/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 84 m², 2 quartos, 3 banheiros, 1 vaga em\nJardim Paulista, São Paulo",
        "street": "Rua José Maria Lisboa",
        "area": "Tamanho do imóvel\n84 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n3",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 29.484/mês",
        "fees": "Cond. R$ 1 • IPTU R$ 1",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-casa-de-condominio-5-quartos-com-piscina-loteamento-alphaville-campinas-campinas-620m2-id-2860422185/?source=ranking%2Crp",
        "location": "Casa de condomínio para alugar com 620 m², 5 quartos, 8 banheiros, 7 vagas em\nLoteamento Alphaville Campinas, Campinas",
        "street": "Avenida Araçá",
        "area": "Tamanho do imóvel\n620 m²",
        "bedrooms": "Quantidade de quartos\n5",
        "bathrooms": "Quantidade de banheiros\n8",
        "parking": "Quantidade de vagas de garagem\n7",
        "price": "R$ 25.000/mês",
        "fees": "Cond. R$ 2.340 • IPTU R$ 2.455",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-loja-salao-com-copa-vila-rezende-piracicaba-68m2-id-2867618968/?source=ranking%2Crp",
        "location": "Ponto comercial/Loja/Box para alugar com 68 m², 2 banheiros em\nVila Rezende, Piracicaba",
        "street": "Rua Maria Manieiro",
        "area": "Tamanho do imóvel\n68 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": None,
        "price": "R$ 1.500/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-com-churrasqueira-recreio-ipitanga-lauro-de-freitas-94m2-id-2864937078/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 94 m², 2 quartos, 2 banheiros, 1 vaga em\nRecreio Ipitanga, Lauro de Freitas",
        "street": "Avenida Santos Dumont",
        "area": "Tamanho do imóvel\n94 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 3.200/mês",
        "fees": "Cond. R$ 1.328 • IPTU R$ 1.222",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-mobiliado-vila-pioneiro-toledo-146m2-id-2868046033/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 146 m², 2 quartos, 2 banheiros, 2 vagas em\nVila Pioneiro, Toledo",
        "street": "Rua Tomás de Aquino",
        "area": "Tamanho do imóvel\n146 m²",
        "bedrooms": "Quantidade de quartos\n2",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n2",
        "price": "R$ 2.200/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-comercial-jardim-sao-gabriel-jacarei-850m2-id-2809600719/?source=ranking%2Crp",
        "location": "Lote/Terreno para alugar com 850 m² em\nJardim São Gabriel, Jacareí",
        "street": "",
        "area": "Tamanho do imóvel\n850 m²",
        "bedrooms": None,
        "bathrooms": None,
        "parking": None,
        "price": "R$ 1.200/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/venda-conjunto-comercial-sala-com-porcelanato-centro-taubate-30m2-id-2841728780/?source=ranking%2Crp",
        "location": "Sala/Conjunto para alugar com 30 m², 1 banheiro em\nCentro, Taubaté",
        "street": "",
        "area": "Tamanho do imóvel\n30 m²",
        "bedrooms": None,
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": None,
        "price": "R$ 1.800/mês",
        "fees": None,
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-piscina-jardim-ana-maria-jundiai-109m2-id-2844960033/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 109 m², 3 quartos, 2 banheiros, 2 vagas em\nJardim Ana Maria, Jundiaí",
        "street": "Rua Elias Juvenal de Mello",
        "area": "Tamanho do imóvel\n109 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n2",
        "price": "R$ 5.300/mês",
        "fees": "Cond. R$ 752 • IPTU R$ 190",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-loja-salao-com-deposito-privativo-indianopolis-sao-paulo-380m2-id-2824253235/?source=ranking%2Crp",
        "location": "Ponto comercial/Loja/Box para alugar com 380 m², 40 vagas em\nIndianópolis, São Paulo",
        "street": "Avenida Rouxinol",
        "area": "Tamanho do imóvel\n380 m²",
        "bedrooms": None,
        "bathrooms": None,
        "parking": "Quantidade de vagas de garagem\n40",
        "price": "R$ 14.000/mês",
        "fees": "IPTU R$ 2.600",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-casa-3-quartos-com-interfone-centro-sorocaba-400m2-id-2847386120/?source=ranking%2Crp",
        "location": "Imóvel comercial para alugar com 400 m², 3 quartos, 2 banheiros, 5 vagas em\nCentro, Sorocaba",
        "street": "Rua Doutor Azevedo Sampaio",
        "area": "Tamanho do imóvel\n400 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n5",
        "price": "R$ 3.500/mês",
        "fees": "IPTU R$ 100",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-cambui-campinas-85m2-id-2847185422/?source=ranking%2Crp",
        "location": "Apartamento para alugar com 85 m², 1 quarto, 2 banheiros, 1 vaga em\nCambuí, Campinas",
        "street": "Rua Coronel Quirino",
        "area": "Tamanho do imóvel\n85 m²",
        "bedrooms": "Quantidade de quartos\n1",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 4.300/mês",
        "fees": "Cond. R$ 929 • IPTU R$ 104",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-conjunto-comercial-sala-3-quartos-com-churrasqueira-jardim-planalto-campinas-111m2-id-2859920503/?source=ranking%2Crp",
        "location": "Sala/Conjunto para alugar com 111 m², 3 quartos, 2 banheiros, 1 vaga em\nJardim Planalto, Campinas",
        "street": "Rua Orlando Fagnani",
        "area": "Tamanho do imóvel\n111 m²",
        "bedrooms": "Quantidade de quartos\n3",
        "bathrooms": "Quantidade de banheiros\n2",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 4.500/mês",
        "fees": "IPTU R$ 388",
    },
    {
        "href": "https://www.zapimoveis.com.br/imovel/aluguel-studio-1-quarto-com-piscina-indianopolis-sao-paulo-37m2-id-2846587143/?source=ranking%2Crp",
        "location": "Imóvel para alugar com 37 m², 1 quarto, 1 banheiro, 1 vaga em\nIndianópolis, São Paulo",
        "street": "Avenida Açocê",
        "area": "Tamanho do imóvel\n37 m²",
        "bedrooms": "Quantidade de quartos\n1",
        "bathrooms": "Quantidade de banheiros\n1",
        "parking": "Quantidade de vagas de garagem\n1",
        "price": "R$ 5.000/mês",
        "fees": "Cond. R$ 870 • IPTU R$ 80",
    },
]
print(len(data))

df = pl.DataFrame(data)

print(df.shape)

df = df.with_columns(
    id_imovel=pl.col("href").str.split("/").list[-2].str.split("id-").list[-1]
)
